name: null
favicon: null
layout_spectrum: 1
typography_spectrum: 0.12712
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-64365008-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#140d0e'
    - '#fefdfc'
    - '#555b64'
    - '#818188'
    - '#ceccd0'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
